# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d5e0e47a0da028c73ffbbbef3d2ae428692c7f06d6f6b46ea186e2d57d7d8ca3bb0df21d28bfd5cce957bf296003519e22909fdb9bf4b7440ab7ddb5ef77722

test:
  secret_key_base: a60e396964aa430aaa153d0ebab5ca8e79095a8fa53a694aa688c2891087d11d17b918ad3c1a80ac4094935f35fb346c70ee72488984675b9d40d939ec26aca8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
